#!/bin/sh
### BEGIN INIT INFO
# Provides:          flapjack-icinga2
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Plugin to support icinga2 on flapjack.io
# Description:       Sends events to flapjack from icinga2 api https://github.com/sol1/flapjack-icinga2
### END INIT INFO

# Do NOT "set -e"
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Sends events to flapjack from icinga2 api"
NAME="flapjack-icinga2"
DAEMON=/bin/flapjack-icinga2
PIDFILE=/var/run/flapjack-icinga2/flapjack-icinga2.pid
LOGFILE=/var/log/flapjack-icinga2/flapjack-icinga2.log
CONFIG=/etc/flapjack-icinga2/flapjack-icinga2.conf

## Read the config file
# Check for existence of needed config file and read it
test -r $CONFIG && . $CONFIG || { echo "$CONFIG not existing";
        if [ "$1" = "stop" ]; then exit 0;
        else exit 6; fi; }

SCRIPT="$DAEMON --icinga-url=$icinga2_server --icinga-user=$icinga_user --icinga-password=$icinga_password --redis-url=$redis_server --debug"

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $user > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
